// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/assignments" | "/admin/groups" | "/admin/groups/[groupId]" | "/admin/trainers" | "/admin/users" | "/admin/users/[userId]" | "/admin/users/new" | "/coach" | "/forgot-password" | "/habits/[id]/edit" | "/habits/new" | "/login" | "/progress" | "/register" | "/reset-password" | "/settings" | "/today"
type AppRouteHandlerRoutes = "/api/admin/assignments/[assignmentId]" | "/api/admin/groups" | "/api/admin/groups/[groupId]" | "/api/admin/users" | "/api/admin/users/[userId]" | "/api/admin/users/[userId]/credentials" | "/api/auth/resolve-login" | "/api/coach/members/[memberId]/habits" | "/api/coach/overview" | "/api/user-state" | "/api/user-state/actions"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/coach"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/assignments": {}
  "/admin/groups": {}
  "/admin/groups/[groupId]": { "groupId": string; }
  "/admin/trainers": {}
  "/admin/users": {}
  "/admin/users/[userId]": { "userId": string; }
  "/admin/users/new": {}
  "/api/admin/assignments/[assignmentId]": { "assignmentId": string; }
  "/api/admin/groups": {}
  "/api/admin/groups/[groupId]": { "groupId": string; }
  "/api/admin/users": {}
  "/api/admin/users/[userId]": { "userId": string; }
  "/api/admin/users/[userId]/credentials": { "userId": string; }
  "/api/auth/resolve-login": {}
  "/api/coach/members/[memberId]/habits": { "memberId": string; }
  "/api/coach/overview": {}
  "/api/user-state": {}
  "/api/user-state/actions": {}
  "/coach": {}
  "/forgot-password": {}
  "/habits/[id]/edit": { "id": string; }
  "/habits/new": {}
  "/login": {}
  "/progress": {}
  "/register": {}
  "/reset-password": {}
  "/settings": {}
  "/today": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/coach": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
